version: "3.7"
services:
  web:
    build: .
    command: gunicorn config.wsgi --bind 0.0.0.0:$PORT
    environment:
      - SECRET_KEY=e!0#xt5#gx-l$vw@xm8=!rotmy(ucuv0_yhc^asx_zxqu@a#g_
      - ENVRIOMENT=production
      - DEBUG=0
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51JK2YfAi50QDrVivgFzcsXehm0EwVaVv34PKgfpa0d45YcjalEoehLPXUuzUw0EKyGdtkcF8aLy2sL4jYWny1iAU00wlGBwZje
      - STRIPE_TEST_SECRET_KEY=sk_test_51JK2YfAi50QDrVivqppsWtj6dcFp6zu8jbO2H9ZabNUbWMxuxNCtDUORaWIA72Ugmjn8wFgnl2tbsa5rgYoizPOq00w79k3O1K
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.7
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
