# Generated by Django 3.2.5 on 2021-08-01 15:07

# from django.db import migrations
# import uuid


# def gen_uuid(apps, schema_editor):
#     MyModel = apps.get_model('books', 'book')
#     for row in MyModel.objects.all():
#         row.uuid = uuid.uuid4
#         row.save(update_fields=['uuid'])


# class Migration(migrations.Migration):

#     dependencies = [
#         ('books', '0002_alter_id_field'),
#     ]

#     operations = [
#         migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
#     ]
